# Generated by Django 4.2.6 on 2023-12-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='prenom',
            field=models.CharField(default='Mr/M.', max_length=50),
        ),
    ]
