# Generated by Django 4.2.6 on 2023-12-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mescontacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=50)),
                ('pays', models.CharField(choices=[('237', 'Cameroun'), ('1', 'France'), ('231', 'Guinee')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
