# Generated by Django 4.2.6 on 2023-12-09 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_mescontacts_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mescontacts',
            new_name='Contact',
        ),
    ]
