# Generated by Django 4.2.6 on 2023-12-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_rename_mescontacts_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='numero_telephone',
            field=models.IntegerField(default=100),
        ),
    ]
